<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>

<!DOCTYPE html>
<html>
<head>
	<jsp:include page="../include/head.jsp"></jsp:include>
	<title>Room Status</title>
</head>
<body>

	<jsp:include page="../include/admin_nav_stretch.jsp"></jsp:include>
	<jsp:include page="../include/admin_nav_sidebar.jsp"></jsp:include>
	
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 my-4">
	
    <div class="text-white">
		<h3>Room Status</h3>
		<hr class="mb-2 shadow-lg">
		</div>
		<div class="table-responsive card card-body bg-white shadow-lg" >
			<table id="roomstatus" class="display roomstatus table table-sm table-striped table-hover p-0" style="width:100%; min-height:100vh;">
				<thead class="bg-cyan text-center">
					<tr>
						<th>Room Number</th>
						<th>Room Type</th>
						<th>Bedding Type</th>
						<th>Occupancy</th>
						<th>Occupied By</th>
						<th>Check-out Date</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>O737</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Occupied</td>
						<td>Claire S. Hayden</td>
						<td>08/13/2021</td>
					</tr>
					<tr>
						<td>A319</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Occupied</td>
						<td>Raymond O. Rivera</td>
						<td>12/01/2020</td>
					</tr>
					<tr>
						<td>A629</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A899</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I340</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Occupied</td>
						<td>Hamilton M. Blackburn</td>
						<td>06/07/2021</td>
					</tr>
					<tr>
						<td>O284</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Occupied</td>
						<td>Elijah I. Leach</td>
						<td>01/28/2021</td>
					</tr>
					<tr>
						<td>I246</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O311</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I954</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Occupied</td>
						<td>Dara D. Cole</td>
						<td>06/12/2021</td>
					</tr>
					<tr>
						<td>I873</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Occupied</td>
						<td>Hashim A. Carey</td>
						<td>07/17/2021</td>
					</tr>
					<tr>
						<td>E527</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A859</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A056</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Occupied</td>
						<td>Zephr B. Roth</td>
						<td>12/05/2020</td>
					</tr>
					<tr>
						<td>E245</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Occupied</td>
						<td>Barry O. Randall</td>
						<td>11/18/2020</td>
					</tr>
					<tr>
						<td>U025</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A229</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I870</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Occupied</td>
						<td>Nero P. Olsen</td>
						<td>10/31/2020</td>
					</tr>
					<tr>
						<td>I382</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Occupied</td>
						<td>Oleg D. Preston</td>
						<td>05/17/2021</td>
					</tr>
					<tr>
						<td>U017</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I414</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>E861</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Occupied</td>
						<td>Tallulah F. Rosa</td>
						<td>12/01/2020</td>
					</tr>
					<tr>
						<td>U696</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Occupied</td>
						<td>Diana O. Clements</td>
						<td>08/18/2021</td>
					</tr>
					<tr>
						<td>A970</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I329</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A367</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Occupied</td>
						<td>Abigail Q. Wong</td>
						<td>08/18/2021</td>
					</tr>
					<tr>
						<td>U576</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Occupied</td>
						<td>Piper F. Riley</td>
						<td>08/01/2021</td>
					</tr>
					<tr>
						<td>U609</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O864</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O424</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Occupied</td>
						<td>Mark O. Alexander</td>
						<td>10/03/2020</td>
					</tr>
					<tr>
						<td>E417</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Occupied</td>
						<td>Addison Z. Stephenson</td>
						<td>10/05/2020</td>
					</tr>
					<tr>
						<td>I380</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O067</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O383</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Occupied</td>
						<td>Lee I. Steele</td>
						<td>04/15/2021</td>
					</tr>
					<tr>
						<td>U503</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Occupied</td>
						<td>Jessamine S. Williamson</td>
						<td>08/10/2021</td>
					</tr>
					<tr>
						<td>I106</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>E336</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O154</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Occupied</td>
						<td>Sopoline Q. Brock</td>
						<td>09/01/2021</td>
					</tr>
					<tr>
						<td>U592</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Occupied</td>
						<td>Camille I. Cline</td>
						<td>03/30/2021</td>
					</tr>
					<tr>
						<td>I662</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O831</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A108</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Occupied</td>
						<td>Berk L. Mcknight</td>
						<td>08/11/2021</td>
					</tr>
					<tr>
						<td>E344</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Occupied</td>
						<td>Scarlet S. Dodson</td>
						<td>11/13/2020</td>
					</tr>
					<tr>
						<td>A331</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A443</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>E605</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Occupied</td>
						<td>Carla P. Bruce</td>
						<td>12/18/2020</td>
					</tr>
					<tr>
						<td>A065</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Occupied</td>
						<td>Freya M. Levine</td>
						<td>03/27/2021</td>
					</tr>
					<tr>
						<td>O043</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O312</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>E975</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>E248</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Occupied</td>
						<td>Giselle P. Fernandez</td>
						<td>09/28/2021</td>
					</tr>
					<tr>
						<td>O461</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>U959</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O917</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Occupied</td>
						<td>Vivien S. Barrett</td>
						<td>10/01/2021</td>
					</tr>
					<tr>
						<td>I893</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Occupied</td>
						<td>Clementine K. Atkinson</td>
						<td>10/27/2021</td>
					</tr>
					<tr>
						<td>I866</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I559</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>U289</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Occupied</td>
						<td>Armando V. Booth</td>
						<td>08/01/2021</td>
					</tr>
					<tr>
						<td>E590</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Occupied</td>
						<td>Vernon I. Park</td>
						<td>11/13/2020</td>
					</tr>
					<tr>
						<td>E744</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>U334</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>U573</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Occupied</td>
						<td>Morgan B. Fox</td>
						<td>12/07/2020</td>
					</tr>
					<tr>
						<td>U398</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Occupied</td>
						<td>Wade Q. Moreno</td>
						<td>01/25/2021</td>
					</tr>
					<tr>
						<td>A295</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>U976</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I684</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Occupied</td>
						<td>Justine A. Navarro</td>
						<td>11/10/2020</td>
					</tr>
					<tr>
						<td>E485</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Occupied</td>
						<td>Zephr A. Ball</td>
						<td>08/09/2021</td>
					</tr>
					<tr>
						<td>U180</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O333</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I893</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Occupied</td>
						<td>Halla Z. Blackwell</td>
						<td>06/06/2021</td>
					</tr>
					<tr>
						<td>I630</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Occupied</td>
						<td>Maggie N. Allison</td>
						<td>09/20/2020</td>
					</tr>
					<tr>
						<td>A871</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O354</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>U135</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Occupied</td>
						<td>Ryan H. Doyle</td>
						<td>11/18/2020</td>
					</tr>
					<tr>
						<td>A414</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Occupied</td>
						<td>Hasad U. Gill</td>
						<td>07/11/2021</td>
					</tr>
					<tr>
						<td>I591</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O195</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I648</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Occupied</td>
						<td>Karen L. Durham</td>
						<td>09/22/2020</td>
					</tr>
					<tr>
						<td>E119</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Occupied</td>
						<td>Adara K. Freeman</td>
						<td>07/05/2021</td>
					</tr>
					<tr>
						<td>O295</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A144</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A466</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Occupied</td>
						<td>Gwendolyn N. Craig</td>
						<td>09/13/2021</td>
					</tr>
					<tr>
						<td>E609</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Occupied</td>
						<td>Aurelia R. Kline</td>
						<td>04/08/2021</td>
					</tr>
					<tr>
						<td>I649</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>E841</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O251</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Occupied</td>
						<td>Veronica K. Spencer</td>
						<td>10/11/2020</td>
					</tr>
					<tr>
						<td>U972</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Occupied</td>
						<td>Ivor Y. Salazar</td>
						<td>11/09/2020</td>
					</tr>
					<tr>
						<td>O611</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O862</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I114</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Occupied</td>
						<td>Elvis Y. Bradshaw</td>
						<td>10/04/2021</td>
					</tr>
					<tr>
						<td>E489</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Occupied</td>
						<td>Rina K. Velazquez</td>
						<td>03/31/2021</td>
					</tr>
					<tr>
						<td>E690</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I799</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>I754</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Occupied</td>
						<td>Tarik D. Houston</td>
						<td>03/11/2021</td>
					</tr>
					<tr>
						<td>E766</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Occupied</td>
						<td>Sophia H. Macias</td>
						<td>08/11/2021</td>
					</tr>
					<tr>
						<td>U457</td>
						<td>Standard</td>
						<td>Twin</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>U187</td>
						<td>Deluxe</td>
						<td>Triple</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>A166</td>
						<td>Standard</td>
						<td>Queen</td>
						<td>Occupied</td>
						<td>Raya U. Beck</td>
						<td>05/17/2021</td>
					</tr>
					<tr>
						<td>E386</td>
						<td>Deluxe</td>
						<td>King</td>
						<td>Occupied</td>
						<td>Jakeem Q. Carter</td>
						<td>10/11/2021</td>
					</tr>
					<tr>
						<td>E655</td>
						<td>Standard</td>
						<td>Double-Double</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>O846</td>
						<td>Deluxe</td>
						<td>Single</td>
						<td>Vacant</td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		
	</main>

	<jsp:include page="../include/footer.jsp"></jsp:include>
	<jsp:include page="../include/scripts.jsp"></jsp:include>
</body>
</html>